/**
 * Downloadable per-client audit folder — a professional PDF dossier and a ZIP of
 * the actual files, both checksummed by a manifest so a recipient can prove the
 * package was not altered. Reuses the pdf-lib layout mechanics + SHA-256 manifest
 * approach from auditPackage.ts, composed over the unified document folder
 * (folder.ts) and the weekly proof-of-delivery view (pod.ts).
 */
import { createHash } from "crypto";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { zipSync, strToU8 } from "fflate";
import { getSubmissionById } from "../db";
import { storageGet } from "../storage";
import { stableStringify } from "./audit";
import { gatherClientDocuments, type FolderDocument } from "./folder";
import { listWeeklyPodForClient, type WeeklyPodEntry } from "./pod";

function sha256Hex(s: string | Uint8Array): string {
  return createHash("sha256").update(s).digest("hex");
}

export interface ClientFolderData {
  submissionId: number;
  clientName: string;
  referenceNumber: string | null;
  documents: FolderDocument[];
  weeklyPod: WeeklyPodEntry[];
}

export async function gatherClientFolder(submissionId: number, opts: { includePrivileged?: boolean } = {}): Promise<ClientFolderData> {
  const submission = await getSubmissionById(submissionId);
  const documents = await gatherClientDocuments(submissionId, opts);
  const weeklyPod = await listWeeklyPodForClient(submissionId);
  const clientName = submission ? `${submission.firstName ?? ""} ${submission.lastName ?? ""}`.trim() || `Client #${submissionId}` : `Client #${submissionId}`;
  return { submissionId, clientName, referenceNumber: submission?.referenceNumber ?? null, documents, weeklyPod };
}

export interface ClientFolderManifest {
  submissionId: number;
  clientName: string;
  generatedAt: string;
  counts: { documents: number; deliveryWeeks: number; missingWeeks: number };
  recordChecksums: { documents: string; weeklyPod: string };
  contentChecksum: string;
  pdfChecksum?: string;
}

export function buildClientManifest(data: ClientFolderData, generatedAtIso: string): ClientFolderManifest {
  const sets = { documents: data.documents, weeklyPod: data.weeklyPod };
  return {
    submissionId: data.submissionId,
    clientName: data.clientName,
    generatedAt: generatedAtIso,
    counts: {
      documents: data.documents.length,
      deliveryWeeks: data.weeklyPod.length,
      missingWeeks: data.weeklyPod.filter((w) => w.missing).length,
    },
    recordChecksums: {
      documents: sha256Hex(stableStringify(sets.documents)),
      weeklyPod: sha256Hex(stableStringify(sets.weeklyPod)),
    },
    contentChecksum: sha256Hex(stableStringify(sets)),
  };
}

// ─── PDF dossier (layout mechanics mirror auditPackage.ts) ────────────────────
export async function renderClientFolderPdf(data: ClientFolderData, manifest: ClientFolderManifest): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const A4: [number, number] = [595.28, 841.89];
  const margin = 50;
  const lineH = 14;
  let page = pdf.addPage(A4);
  let y = A4[1] - margin;
  const newPage = () => { page = pdf.addPage(A4); y = A4[1] - margin; };
  const ensure = (need = lineH) => { if (y - need < margin) newPage(); };
  const write = (text: string, opts?: { size?: number; bold?: boolean; color?: [number, number, number] }) => {
    const size = opts?.size ?? 10;
    const f = opts?.bold ? bold : font;
    const c = opts?.color ?? [0.1, 0.1, 0.1];
    const maxChars = Math.floor((A4[0] - 2 * margin) / (size * 0.5));
    const words = String(text).split(/\s+/);
    let line = "";
    const flush = () => { ensure(size + 4); page.drawText(line, { x: margin, y, size, font: f, color: rgb(c[0], c[1], c[2]) }); y -= size + 4; line = ""; };
    for (const w of words) { if ((line + " " + w).trim().length > maxChars) flush(); line = (line ? line + " " : "") + w; }
    if (line) flush();
  };
  const heading = (t: string) => { y -= 6; ensure(18); write(t, { size: 13, bold: true, color: [0.09, 0.4, 0.15] }); y -= 2; };
  const kv = (k: string, v: unknown) => write(`${k}: ${v ?? "—"}`);

  // Cover
  y -= 120;
  write("Client Audit Folder", { size: 22, bold: true, color: [0.09, 0.4, 0.15] });
  y -= 10;
  write(data.clientName, { size: 15, bold: true });
  y -= 6;
  write(`Reference: ${data.referenceNumber ?? "—"}    Client ID: ${data.submissionId}`, { size: 11 });
  write(`Generated: ${manifest.generatedAt}`, { size: 11 });
  y -= 20;
  write("Generated by the FreshSelect Meals compliance module. This dossier lists the documents and weekly proof-of-delivery on record for this client. It does not constitute a legal determination or a guarantee of compliance or reimbursement.", { size: 9, color: [0.4, 0.4, 0.4] });

  // 1. Document index
  newPage();
  heading("1. Document Index");
  if (data.documents.length === 0) write("No documents on file.");
  data.documents.forEach((d, i) => {
    write(`${i + 1}. ${d.name}`, { bold: true });
    write(`   source: ${d.source}${d.category ? `, category: ${d.category}` : ""}${d.confidentiality && d.confidentiality !== "standard" ? `, ${d.confidentiality}` : ""}`);
    if (d.checksum) write(`   checksum (SHA-256): ${d.checksum}`);
    write(`   handle: ${d.fileKey ?? d.url ?? "—"}`, { color: [0.4, 0.4, 0.4] });
  });

  // 2. Weekly proof of delivery
  heading("2. Weekly Proof of Delivery");
  if (data.weeklyPod.length === 0) write("No delivery weeks recorded.");
  data.weeklyPod.forEach((w) => {
    const status = w.missing ? "MISSING PROOF" : (w.podUrl ? "proof on file" : (w.status ?? "on file"));
    write(`• Week of ${w.weekOf} (${w.weekLabel}) — ${status}${w.vendorName ? `, vendor: ${w.vendorName}` : ""}${w.podMethod ? `, method: ${w.podMethod}` : ""}`, w.missing ? { color: [0.7, 0.4, 0] } : undefined);
    if (w.podUrl) write(`   ${w.podUrl}`, { color: [0.2, 0.2, 0.6] });
  });

  // 3. Manifest
  heading("3. Manifest & Checksums");
  kv("Client ID", manifest.submissionId);
  kv("Generated", manifest.generatedAt);
  kv("Documents", manifest.counts.documents);
  kv("Delivery weeks", manifest.counts.deliveryWeeks);
  kv("Weeks missing proof", manifest.counts.missingWeeks);
  kv("Documents checksum", manifest.recordChecksums.documents);
  kv("Weekly PoD checksum", manifest.recordChecksums.weeklyPod);
  kv("Content checksum (SHA-256)", manifest.contentChecksum);

  return pdf.save();
}

export interface GeneratedClientFolderPdf {
  filename: string;
  pdfBytes: Uint8Array;
  manifest: ClientFolderManifest;
}

/** Full PDF generation: gather → manifest → PDF → attach pdfChecksum. */
export async function generateClientFolderPdf(submissionId: number, opts: { includePrivileged?: boolean } = {}): Promise<GeneratedClientFolderPdf> {
  const data = await gatherClientFolder(submissionId, opts);
  const generatedAtIso = new Date().toISOString();
  const manifest = buildClientManifest(data, generatedAtIso);
  const pdfBytes = await renderClientFolderPdf(data, manifest);
  manifest.pdfChecksum = sha256Hex(pdfBytes);
  return { filename: `client-${submissionId}-audit-folder-${generatedAtIso.slice(0, 10)}.pdf`, pdfBytes, manifest };
}

// ─── ZIP of the actual files ──────────────────────────────────────────────────
const ZIP_MAX_FILES = 200;
const ZIP_MAX_BYTES_PER_FILE = 25 * 1024 * 1024; // 25 MB
const ZIP_MAX_TOTAL_BYTES = 200 * 1024 * 1024; // 200 MB

/** Fetch a document's bytes from storage (best-effort; null on any failure). */
async function fetchDocBytes(doc: FolderDocument): Promise<Uint8Array | null> {
  try {
    let url: string | null = null;
    if (doc.fileKey) { url = (await storageGet(doc.fileKey)).url; }
    else if (doc.url) { url = doc.url; }
    if (!url) return null;
    const res = await fetch(url);
    if (!res.ok) return null;
    const len = Number(res.headers.get("content-length") ?? 0);
    if (len && len > ZIP_MAX_BYTES_PER_FILE) return null;
    const buf = new Uint8Array(await res.arrayBuffer());
    if (buf.byteLength > ZIP_MAX_BYTES_PER_FILE) return null;
    return buf;
  } catch { return null; }
}

/** Sanitize a document name into a safe, unique zip entry filename. */
function safeEntryName(name: string, index: number, mime: string | null): string {
  const base = name.replace(/[^A-Za-z0-9._-]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 80) || `document-${index}`;
  const hasExt = /\.[A-Za-z0-9]{1,6}$/.test(base);
  const ext = hasExt ? "" : (mime === "application/pdf" ? ".pdf" : mime?.startsWith("image/") ? `.${mime.slice(6)}` : "");
  return `${String(index + 1).padStart(3, "0")}-${base}${ext}`;
}

export interface GeneratedClientFolderZip {
  filename: string;
  zipBytes: Uint8Array;
  manifest: ClientFolderManifest;
  included: number;
  unavailable: number;
}

/**
 * Build a ZIP with: the PDF dossier, an index.csv, a manifest.json, and every
 * document file that could be fetched from storage (capped). Files that can't be
 * fetched are listed in index.csv as "unavailable" so the archive is always
 * valid and honest about what it contains.
 */
export async function generateClientFolderZip(submissionId: number, opts: { includePrivileged?: boolean } = {}): Promise<GeneratedClientFolderZip> {
  const data = await gatherClientFolder(submissionId, opts);
  const generatedAtIso = new Date().toISOString();
  const manifest = buildClientManifest(data, generatedAtIso);
  const pdfBytes = await renderClientFolderPdf(data, manifest);
  manifest.pdfChecksum = sha256Hex(pdfBytes);

  const files: Record<string, Uint8Array> = {};
  files["audit-folder.pdf"] = pdfBytes;

  const indexRows: string[] = ["index,name,source,category,checksum,status,zipEntry"];
  let included = 0, unavailable = 0, totalBytes = pdfBytes.byteLength;
  for (let i = 0; i < data.documents.length && i < ZIP_MAX_FILES; i++) {
    const d = data.documents[i];
    let status = "unavailable";
    let entry = "";
    if (totalBytes < ZIP_MAX_TOTAL_BYTES) {
      const bytes = await fetchDocBytes(d);
      if (bytes && totalBytes + bytes.byteLength <= ZIP_MAX_TOTAL_BYTES) {
        entry = `files/${safeEntryName(d.name, i, d.mimeType)}`;
        files[entry] = bytes;
        totalBytes += bytes.byteLength;
        included++;
        status = "included";
      }
    }
    if (status !== "included") unavailable++;
    const csv = (s: unknown) => `"${String(s ?? "").replace(/"/g, '""')}"`;
    indexRows.push([i + 1, csv(d.name), d.source, csv(d.category ?? ""), d.checksum ?? "", status, csv(entry)].join(","));
  }

  files["index.csv"] = strToU8(indexRows.join("\r\n"));
  files["manifest.json"] = strToU8(JSON.stringify(manifest, null, 2));

  const zipBytes = zipSync(files, { level: 6 });
  return { filename: `client-${submissionId}-audit-folder-${generatedAtIso.slice(0, 10)}.zip`, zipBytes, manifest, included, unavailable };
}
